name: node-microservices-app
description: sample app demonstrating a basic microservice in Nodejs
keywords:
  - Nodejs
  - microservices
  - express
  - postgres

secrets:
  catalog_db_name:
    description: name of the catalog database
    default: postgres
  catalog_db_user:
    description: main user for the catalog database
    default: postgres
  catalog_db_pass:
    description: password for the catalog database user
    default: postgres

interfaces:
  app:
    url: ${{ services.app.interfaces.main.url }}
    ingress:
      subdomain: app
  catalog-service:
    url: ${{ services.catalog-service.interfaces.main.url }}
    ingress:
      subdomain: api

services:
  catalog-service-db:
    image: postgres
    interfaces: 
      postgres:
        port: 5432
        username: ${{ secrets.catalog_db_user }}
        password: ${{ secrets.catalog_db_pass }}
        protocol: postgres
    environment:
      POSTGRES_USER: ${{ secrets.catalog_db_user }}
      POSTGRES_PASSWORD: ${{ secrets.catalog_db_pass }}
      POSTGRES_DB: ${{ secrets.catalog_db_name }}
    volumes:
      data:
        mount_path: /var/lib/postgresql/data
      initdb:
        mount_path: /docker-entrypoint-initdb.d
    debug:
      volumes:
        data:
          host_path: ./data
        initdb:
          host_path: ./sql

  catalog-service:
    depends_on:
      - catalog-service-db
    build:
      context: ./catalog-service
      args:
        NODE_ENV: production
    interfaces:
      main:
        port: 3001
    environment:
      PORT: ${{ services.catalog-service.interfaces.main.port }}
      DB_DSN: ${{ services.catalog-service-db.interfaces.postgres.url }}/${{ secrets.catalog_db_name }}
    debug:
      command: npm start
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          mount_path: /app/src
          host_path: ./catalog-service/src

  app:
    depends_on:
      - catalog-service
    build:
      context: ./webapp
      args:
        NODE_ENV: production
    interfaces:
      main: &app-port 3000
    environment:
      PORT: *app-port
      CATALOG_SVC_ADDR: ${{ services.catalog-service.interfaces.main.url }}
    debug:
      build: 
        args:
          NODE_ENV: development
      volumes:
        src:
          mount_path: /app/src
          host_path: ./webapp/src
