version: '3'

services:
  webapp:
    build: ./webapp/
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
    environment:
      - CATALOG_SVC_ADDR=http://catalog-service:3001

  catalog-service:
    build: ./catalog-service/
    volumes:
      - ./catalog-service:/app
    ports:
      - "3001:3001"
    environment:
      - DB_ADDR=localhost

  catalog-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
      
volumes:
  db:
    driver: local